@startuml custom
actor Customer
boundary "System" as system
control "Customization" as custom
control "Payment" as pay
Customer -> system: custom order 
activate system
system -> custom: custom request
activate custom
activate pay
custom -> pay: money(price)
pay --> system: payment(total)
deactivate pay
custom --> system: order(flavor, frosting, filling1, filling2, toppings, price, date, time)
deactivate custom
system -> system: redirect to receiving method screen
deactivate system
@enduml